### ISSUE TITLE
是否考虑支持Bangumi？

### ISSUE THREAD

**Issue by TwooSix** [Roozenlz/plugin-bilibili-bangumi#3]
[Bangumi](https://bangumi.tv/)作为追番记录来说番剧信息会比较完善一点，而且也有官方提供的API：https://github.com/bangumi/api

**Comment by Roozenlz** [comment]
那是不是还需要去[Bangumi](https://bangumi.tv/)注册一个账户，然后收藏对应的番剧？

**Comment by TwooSix** [comment]
> 那是不是还需要去[Bangumi](https://bangumi.tv/)注册一个账户，然后收藏对应的番剧？

是的，就是这么一种基于个人账号+番剧收藏+手动记录追番进度的方式

**Comment by Roozenlz** [comment]
这个api我看了，数据格式和bilibili肯定是不一样的，而且有些数据没有，使用起来也不方便，需要自己一个一个把番剧收藏，暂时不考虑支持

**Comment by TwooSix** [comment]
> 这个api我看了，数据格式和bilibili肯定是不一样的，而且有些数据没有，使用起来也不方便，需要自己一个一个把番剧收藏，暂时不考虑支持

ok，感谢回复
