### ISSUE TITLE
希望能够开发douban collection的插件

### ISSUE THREAD

**Issue by jiehua1995** [Roozenlz/plugin-bilibili-bangumi#4]
非常喜欢hexo.js的hexo-douban插件，但是切换到halo后没有类似的插件
[plugin-bilibili-bangumi](https://github.com/Roozenlz/plugin-bilibili-bangumi) 非常好看非常完美

不知道能不能开发douban相关的插件嘞？

谢谢！

**Comment by Roozenlz** [comment]
douban不是已经上架应用市场了吗

**Comment by jiehua1995** [comment]
谢谢！当时可能没有找到豆瓣插件
